version: '{build}'
image:
  - Visual Studio 2017
  - Ubuntu
skip_commits:
  files:
    - '*.md'
    - '*.txt'
branches:
  only:
    - master
  except:
    - /.+[\-.]wip$/
    - wip
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
install:
- cmd: curl -O https://download.visualstudio.microsoft.com/download/pr/53f250a1-318f-4350-8bda-3c6e49f40e76/e8cbbd98b08edd6222125268166cfc43/dotnet-sdk-3.0.100-win-x64.exe
- sh: curl -O https://dot.net/v1/dotnet-install.sh
- sh: chmod +x dotnet-install.sh
- ps: |
    if ($isWindows) { dotnet-sdk-3.0.100-win-x64.exe -q }
    if ($isLinux)   { ./dotnet-install.sh --version $sdkVersion }
- sh: ./dotnet-install.sh --version 2.2.7 --runtime dotnet
- sh: ./dotnet-install.sh --version 2.1.3 --runtime dotnet
- sh: export PATH="$HOME/.dotnet:$PATH"
before_build:
- dotnet --info
build_script:
- ps: >-
    $id = $env:APPVEYOR_REPO_COMMIT_TIMESTAMP -replace '([-:]|\.0+Z)', ''

    $id = $id.Substring(0, 13)

    if ($isWindows) { .\pack.cmd ci-$id } else { ./pack.sh ci-$id }
- sh: export PATH="$HOME/.dotnet:$PATH"
test_script:
- cmd: test.cmd
- sh: ./test.sh
- sh: # revert to following post merge of PR codecov/codecov-bash#138
- sh: # curl -s https://codecov.io/bash > codecov
- sh: curl -s https://raw.githubusercontent.com/codecov/codecov-bash/14662d32a4862918c31efafe4b450de1305a38e1/codecov > codecov
- sh: chmod +x codecov
- sh: ./codecov -f ./tests/coverage.opencover.xml
artifacts:
- path: dist\*.nupkg
deploy:
- provider: NuGet
  server: https://www.myget.org/F/raboof/api/v2/package
  api_key:
    secure: fhGwXyO35FSshRzs5GWmF1LJTrd1sIqmS/jNCSfO2LfOciuYAKiXuFMYZFGiTAl+
  symbol_server: https://www.myget.org/F/raboof/symbols/api/v2/package
  on:
    branch: master
notifications:
- provider: Email
  to:
  - raboof-ci@googlegroups.com
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
